language: php
php:
  - 7.2
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
    - php: 7.2
before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
  - cp .env.dist .env
script:
 - phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
