language: php
php:
  - 7.0
  - 7.1
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
    - php: 7.0
    - php: 7.1
before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
  - cp .env.dist .env
script:
 - if [ $(phpenv version-name) != "7.1" ]; then phpunit; fi
 - if [ $(phpenv version-name) == "7.1" ]; then phpunit --coverage-text --coverage-clover=coverage.clover; fi
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ $(phpenv version-name) == "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
